import {
  Box,
  Button,
  Flex,
  FormControl,
  Heading,
  Input,
  Stack,
  Text,
} from "@chakra-ui/react";
import { FormEvent, useState } from "react";

import Head from "next/head";
import type { NextPage } from "next";
import { useAuth } from "@lib/contexts/auth";
import { useFormFields } from "@lib/hooks/useFormFields";

type SignInFieldProps = {
  email: string;
};

const FORM_VALUES: SignInFieldProps = {
  email: "",
};

const Login: NextPage = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [message, setMessage] = useState<{ type?: string; content?: string }>({
    type: "",
    content: "",
  });
  const [submitted, setSubmitted] = useState<boolean>(false);

  const { signIn } = useAuth();

  const [values, handleChange, resetFormFields] =
    useFormFields<SignInFieldProps>(FORM_VALUES);

  const handleSignin = async (e: FormEvent<Element>) => {
    e.preventDefault();

    setLoading(true);
    const { error } = await signIn(values);

    if (error) {
      setMessage({
        type: "error",
        content: error.message,
      });
      setLoading(false);
      return;
    }

    setLoading(false);
    resetFormFields();
    setSubmitted(true);
  };

  return (
    <div>
      <Head>
        <title>Login page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!submitted ? (
        <Flex minH={"100vh"} align={"center"} justify={"center"} bg={"black"}>
          <Stack
            spacing={4}
            w={"full"}
            maxW={"md"}
            bg={"whiteAlpha.900"}
            rounded={"xl"}
            p={6}
          >
            <Heading
              color="gray.900"
              lineHeight={1.1}
              fontSize={{ base: "2xl", md: "3xl" }}
            >
              Login
            </Heading>
            <Text fontSize={{ base: "sm", sm: "md" }} color={"gray.800"}>
              You&apos;ll get an email with a login link
            </Text>
            <FormControl id="email">
              <Input
                border={"2px solid"}
                borderColor="gray.500"
                _hover={{
                  borderColor: "gray.800",
                }}
                _focus={{
                  outline: "none",
                }}
                name="email"
                placeholder="your-email@example.com"
                _placeholder={{ color: "gray.500" }}
                color="gray.800"
                type="email"
                autoComplete="off"
                value={values.email}
                onChange={(e: any) => {
                  handleChange(e);
                }}
              />
            </FormControl>
            <Stack spacing={6}>
              <Button
                isLoading={loading}
                bg={"blue.400"}
                color={"white"}
                _hover={{
                  bg: "blue.500",
                }}
                onClick={(e: FormEvent) => handleSignin(e)}
              >
                Login
              </Button>
            </Stack>
          </Stack>
        </Flex>
      ) : (
        <Box
          py={{ base: 20, md: 36 }}
          maxW="50%"
          mx="auto"
          display={"flex"}
          flexDirection="column"
          w="100%"
          h="100vh"
          justifyContent="center"
          alignItems="center"
        >
          <Heading mb={4} as="h1" size="2xl">
            Link Sent!
          </Heading>
          <Text fontSize={"xl"}>
            Please, check your inbox for your login link.
          </Text>
        </Box>
      )}
    </div>
  );
};

export default Login;
